In [1]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from utils import *
from data import *
from find_targets import *
from debug_tools import *
import json

In [2]:
path3 = "../ModulePictures/P1014_20UPGM23211689_AfterWirebonding.jpg"
path1 = "../ModulePictures/P1004_20UPGM23211223_AfterBonding_NOK.jpg"
path2 = "../ModulePictures/P1005_20UPGM23211816_AfterBonding_NOK.jpg"
path4 = "../ModulePictures/P1015_20UPGM23210321_AfterWirebonding.jpg"
ref_unbonded = "../ModulePictures/Ref_img_unbonded.jpg"
ref_bonded = "../ModulePictures/Ref_img_bonded.jpg"

In [3]:
img = cv.imread(ref_bonded)
H = compute_homography_center(cv.imread(ref_unbonded),cv.imread(ref_bonded))

with open("REF_TRACKS.json") as f:
    data = json.load(f)
    for track in data.values():

        track_bonded = warp_points(track, H).astype(np.int32)

        if len(track_bonded)==2 : 
            cv.rectangle(img,track_bonded[0], track_bonded[1], (0, 255, 0), 3)
        elif len(track_bonded)>0 :
            cv.polylines(img,[np.array(track_bonded).reshape((-1,1,2))], True, (0, 255, 0), 3)
    imS = cv.resize(img, (2000, 2000)) 
    cv.imshow("result",imS)
    cv.waitKey(0)
    cv.destroyAllWindows()

In [16]:
targets_dst = find_targets_wired(path3)
targets_ref = find_targets_wired(ref_bonded)
img = cv.imread(path3)

H1 = cv.findHomography(targets_ref, targets_dst, cv.RANSAC)[0]
H2 = compute_homography_center(cv.imread(ref_unbonded),cv.imread(ref_bonded))

with open("REF_TRACKS.json") as f:
    data = json.load(f)
    for track in data.values():

        track_bonded = warp_points(track, H2).astype(np.int32)
        track_dst = warp_points(track_bonded, H1).astype(np.int32)

        if len(track_dst)==2 : 
            cv.rectangle(img,track_dst[0], track_dst[1], (0, 255, 0), 3)
        elif len(track_dst)>0 :
            cv.polylines(img,[np.array(track_dst).reshape((-1,1,2))], True, (0, 255, 0), 3)
    imS = cv.resize(img, (2000, 2000)) 
    cv.imshow("result",imS)
    cv.waitKey(0)
    cv.destroyAllWindows()

In [17]:
def find_tracks(path, draw = False):

    ref_bonded = "../ModulePictures/Ref_img_bonded.jpg"

    targets_dst = find_targets_wired(path)
    targets_ref = find_targets_wired(ref_bonded) # Changer par la ref

    H1 = cv.findHomography(targets_ref, targets_dst, cv.RANSAC)[0]
    H2 = compute_homography_center(cv.imread(ref_unbonded),cv.imread(ref_bonded))

    tracks = []
    if draw :
        img = cv.imread(path).copy()

    with open("REF_TRACKS.json") as f:
        data = json.load(f)
        for track in data.values():

            track_bonded = warp_points(track, H2).astype(np.int32)
            track_dst = warp_points(track_bonded, H1).astype(np.int32)
            tracks.append(track_dst)
    
            if draw :
                if len(track_dst)==2 : 
                    cv.rectangle(img,track_dst[0], track_dst[1], (0, 255, 0), 3)
                elif len(track_dst)>0 :
                    cv.polylines(img,[np.array(track_dst).reshape((-1,1,2))], True, (0, 255, 0), 3)

    if draw :
        imS = cv.resize(img, (2000, 2000)) 
        cv.imshow("result",imS)
        cv.waitKey(0)
        cv.destroyAllWindows()

    return tracks

In [18]:
find_tracks(path3)

[array([[1150,  253],
        [1275,  264]], dtype=int32),
 array([[1147,  277],
        [1277,  288]], dtype=int32),
 array([[1147,  303],
        [1277,  316]], dtype=int32),
 array([[1200,  327],
        [1277,  341]], dtype=int32),
 array([[1212,  353],
        [1278,  366]], dtype=int32),
 array([[1182,  357],
        [1195,  356],
        [1196,  380],
        [1278,  379],
        [1277,  391],
        [1184,  393]], dtype=int32),
 array([[1196,  434],
        [1277,  486]], dtype=int32),
 array([[1197,  497],
        [1276,  579]], dtype=int32),
 array([[1196,  594],
        [1275,  642]], dtype=int32),
 array([[1182,  776],
        [1274,  773],
        [1275,  787],
        [1193,  788],
        [1193,  811],
        [1182,  812]], dtype=int32),
 array([[1209,  801],
        [1275,  812]], dtype=int32),
 array([[1197,  827],
        [1272,  837]], dtype=int32),
 array([[1197,  853],
        [1272,  864]], dtype=int32),
 array([[1199,  877],
        [1274,  889]], dtype=int32)