In [3]:
import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
from utils import *
from data import *
from find_targets import *
from debug_tools import *
from wire import *
from count import *

In [4]:
path3 = "../ModulePictures/P1014_20UPGM23211689_AfterWirebonding.jpg"
path1 = "../ModulePictures/P1004_20UPGM23211223_AfterBonding_NOK.jpg"
path2 = "../ModulePictures/P1005_20UPGM23211816_AfterBonding_NOK.jpg"
path4 = "../ModulePictures/P1015_20UPGM23210321_AfterWirebonding.jpg"
ref = "../ModulePictures/Ref_img_unbonded.jpg"
ref_bonded = "../ModulePictures/Ref_img_bonded.jpg"

In [5]:
targets = find_targets_wired(path3)
targets

array([[1076,  287],
       [1053, 5218],
       [1191, 2708],
       [1191, 2800],
       [5880,  292],
       [5875, 5239],
       [5750, 2719],
       [5750, 2812]], dtype=int32)

In [6]:
def find_ROI(targets, margins=(350, 250, 450, 100)):
    # Find the bounding box of the targets

    #Left side
    if targets[0] is not None: # Top left target
        xmin_left = targets[0,0] - margins[0]
        xmax_left = targets[0,0] + margins[1]

    if targets[1] is not None: # Bottom left target
        xmin_left = targets[1,0] - margins[0]
        xmax_left = targets[1,0] + margins[1]

    elif targets[2] is not None: #High left middle target
        xmin_left = targets[2,0] - margins[2]
        xmax_left = targets[2,0] + margins[3]

    elif targets[3] is not None: #Low left middle target
        xmin_left = targets[3,0] - margins[2]
        xmax_left = targets[3,0] + margins[3]
    
    else:
        raise ValueError("Not enough left targets found") #Improbable qu'on arrive ici, ça posera d'autres problèmes bien avant.
    

    # Right side
    if targets[4] is not None: # Top right target
        xmin_right = targets[4,0] + margins[0]
        xmax_right = targets[4,0] - margins[1]

    if targets[5] is not None: # Bottom right target
        xmin_right = targets[5,0] + margins[0]
        xmax_right = targets[5,0] - margins[1]

    elif targets[6] is not None: #High right middle target
        xmin_right = targets[6,0] + margins[2]
        xmax_right = targets[6,0] - margins[3] 

    elif targets[7] is not None: #Low right middle target
        xmin_right = targets[7,0] + margins[2]
        xmax_right = targets[7,0] - margins[3]
    
    else:
        raise ValueError("Not enough right targets found")
    

    return (xmin_left, xmax_left), (xmin_right, xmax_right)

In [7]:
def kernel_wheel(shape):
    x, y = shape
    kernels = []
    
    for i in range(y // 2 + y % 2):
        height = y - 2 * i
            
        mat = np.zeros((height, x), dtype=np.uint8)
        
        for j in range(height):
            start_col = int(j * x / height)
            end_col = int(np.ceil((j + 1) * x / height))
            
            mat[j, start_col:end_col] = 1
            
        kernels.append(mat)
        
        if height > 1 or i == 0:
            kernels.append(np.flip(mat, axis=1))
            
    return kernels

In [8]:
def label2rgb(labels):
  """
  Convert a labels image to an rgb image using a matplotlib colormap
  """
  label_range = np.linspace(0, 1, 256)
  lut = np.uint8(plt.cm.viridis(label_range)[:,2::-1]*256).reshape(256, 1, 3) # replace viridis with a matplotlib colormap of your choice
  return cv.LUT(cv.merge((labels, labels, labels)), lut)

def gen_lut():
  """
  Generate a label colormap compatible with opencv lookup table, based on
  Rick Szelski algorithm in `Computer Vision: Algorithms and Applications`,
  appendix C2 `Pseudocolor Generation`.
  :Returns:
    color_lut : opencv compatible color lookup table
  """
  tobits = lambda x, o: np.array(list(np.binary_repr(x, 24)[o::-3]), np.uint8)
  arr = np.arange(256)
  r = np.concatenate([np.packbits(tobits(x, -3)) for x in arr])
  g = np.concatenate([np.packbits(tobits(x, -2)) for x in arr])
  b = np.concatenate([np.packbits(tobits(x, -1)) for x in arr])
  return np.concatenate([[[b]], [[g]], [[r]]]).T

def labels2rgb(labels, lut):
  """
  Convert a label image to an rgb image using a lookup table
  :Parameters:
    labels : an image of type np.uint8 2D array
    lut : a lookup table of shape (256, 3) and type np.uint8
  :Returns:
    colorized_labels : a colorized label image
  """
  return cv2.LUT(cv2.merge((labels, labels, labels)), lut)

In [9]:
def find_ROI(img):
    n = img.shape[1]

    high_left, low_left = crop_ligns(img[:,:n//2])
    high_right, low_right = crop_ligns(img[:,n//2:])
    grey = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    left = crop_columns_left(grey[high_left:low_left])
    right = crop_columns_right(grey[high_right:low_right])

    return ((left, left + 500),(low_left, high_left), (right-500,right), (low_right,high_right))


In [10]:
def wire_threshold(img, draw = False):

    # Retire les portions les plus jaunes ou gris foncé de l'image
    hsv = cv.cvtColor(img, cv.COLOR_BGR2HSV)
    _,S,V = cv.split(hsv)
    satmask = cv.inRange(S, 0, 60)
    valmask = cv.inRange(V, 200,255)
    colormask = cv.bitwise_and(satmask,valmask)

    # Retire les parties les moins lumineuses de l'image
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    blurred = cv.GaussianBlur(gray,(5,5),0)
    intensitymask = cv.adaptiveThreshold(blurred, 255, cv.ADAPTIVE_THRESH_MEAN_C, cv.THRESH_BINARY, 25, -25)
    

    # Resultat
    mask = cv.bitwise_and(intensitymask,colormask)

    # Nettoyage : passage d'un kernel horizontal
    closing_kernel = cv.getStructuringElement(cv.MORPH_RECT, (5,1))
    closed = cv.morphologyEx(mask,cv.MORPH_DILATE, closing_kernel) # Fermeture

    kernels = kernel_wheel((9,7))  # Retrait des "blobs" a l'aide de noyaux customisés (diagonale "tournante")
    clean = cv.morphologyEx(closed, cv.MORPH_OPEN, kernels[0])
    for kernel in kernels[1:]:
        clean = cv.bitwise_or(clean,cv.morphologyEx(closed, cv.MORPH_OPEN, kernel))

    # # Detection des fils qui se touchent
    # vkernel = cv.getStructuringElement(cv.MORPH_RECT, (1,7)) 
    # eroded = cv.morphologyEx(clean,cv.MORPH_ERODE, vkernel) # Erosion verticale
    # connections = cv.morphologyEx(eroded,cv.MORPH_CLOSE, closing_kernel) 
    # connections = cv.bitwise_and(clean, connections)

    # retval, _, stats, centroids = cv.connectedComponentsWithStats(connections)
    # print(f"Found {retval} connected components.")
    
    # # Ne garder que les composants qui ont une aire suffisante pour ne pas être du bruit (a priori un contact ne se fait pas en un seul pixel)
    # centers = []
    # if draw:
    #     cimg = img.copy()

    # for i in range(1, retval):
    #     area = stats[i, cv.CC_STAT_AREA]
        
    #     if area < 10:   
    #         continue
        
    #     cx, cy = centroids[i]
    #     centers.append([int(cx), int(cy)])

    #     if draw :
    #         cv.circle(cimg, (int(cx), int(cy)), 20, (0,0,255), 3)

    # if draw :
    #     magnifying_glass(cimg)




    # #Computing the skeleton
    # skeleton_kernel = cv.getStructuringElement(cv.MORPH_CROSS, (3,3))
    # skeleton = np.zeros(clean.shape, dtype=np.uint8)
    # temp = clean.copy()
    # while cv.countNonZero(temp)!=0:
    #     temp_opened = cv.morphologyEx(temp, cv.MORPH_OPEN, skeleton_kernel)
    #     skeleton = cv.bitwise_or(skeleton, cv.bitwise_and(temp, 255-temp_opened)) # skeleton = skeleton | (img & !open(img))
    #     temp = cv.morphologyEx(temp, cv.MORPH_ERODE, skeleton_kernel)


    # edge_kernel =  np.full((5,3),-1)
    # edge_kernel[3,1] = 5*3 - 1
    # a = cv.filter2D(skeleton,ddepth = -1, kernel=edge_kernel)

    # magnifying_glass(skeleton)
    # magnifying_glass(a)

    return clean

In [55]:
def find_shorts(path, draw = False):

    img = cv.imread(path)
    ROI = find_ROI(img)
    mask = img[ROI[1][1]:ROI[1][0], ROI[0][0]:ROI[0][1]]

    processed = wire_threshold(mask, draw)

    retval, labels, stats, _ = cv.connectedComponentsWithStats(processed, connectivity = 4)
    y_left, x_left, y_right, x_right = wire_pos(img)

    y_left_ROI = y_left - ROI[1][1]
    x_left_ROI = x_left - ROI[0][0]
    seen_labels = np.full(retval, False)

    if draw : 
        cimg = mask.copy()

    short_list = []
    edge_list = []

    for y_wire in y_left_ROI:

        label = labels[y_wire, x_left_ROI]
           
        x = stats[label, cv.CC_STAT_LEFT]
        y = stats[label, cv.CC_STAT_TOP]
        w = stats[label, cv.CC_STAT_WIDTH]
        h = stats[label, cv.CC_STAT_HEIGHT]

        region = processed[y:y+h, x:x+w]*(labels[y:y+h, x:x+w] == label) #Extraire la region où il y a le fil
        region = cv.copyMakeBorder(region,5,5,5,5,cv.BORDER_CONSTANT, value = 0) #Rajouter des bords noirs sur les cotes pour pas avoir de mauvaises surprises


        if seen_labels[label]:  # On verifie qu'on ne voit qu'une fois chaque label, sinon c'est qu'il y a un court-circuit

            vkernel = cv.getStructuringElement(cv.MORPH_RECT, (5,7)) # Rectangle 5x7
            hkernel = cv.getStructuringElement(cv.MORPH_RECT, (25,3))
            no_wires = cv.morphologyEx(region, cv.MORPH_ERODE, vkernel) # Il ne reste que les endroits des courts-circuits (fil plus epais, et notamment plus large)
            shorts = cv.morphologyEx(no_wires, cv.MORPH_DILATE, hkernel) # Si plusieurs contacts dans la zone, on essaye de les relier pour minimiser le nombre de cercles

            if draw : 
                magnifying_glass(region)
                magnifying_glass(mask[y:y+h, x:x+w])

            nb_shorts,_,short_stats,short_centers = cv.connectedComponentsWithStats(shorts) #On trouve les emplacement des differents courts-circuits
            
            for i in range(nb_shorts):
                if short_stats[i, cv.CC_STAT_LEFT] > 5 : # Eviter de prendre en compte les pads tout à gauche, où le fil est plus gros
                    # TODO : penser au fait que ça doit marcher des deux côtés
                    short_list.append(short_centers[i].astype(np.uint8) + np.array([x,y]))

                    if draw:
                        cx, cy = short_centers[i]
                        cv.circle(cimg, (int(cx+x), int(cy+y)), 20, (0,0,255), 3)
            
        else :
            seen_labels[labels[y_wire, x_left_ROI]] = True # On verifie qu'on ne voit qu'une fois chaque label, sinon c'est qu'il y a un court-circuit
        
        
        # On trouve le point de soudure
        right_col = np.max(np.where(region >0)[1]) # La colonne la plus à droite de l'image, ou il reste du blanc
        right_pixels_y = np.where(region[:, right_col] > 0)[0] # Tous les pixels blancs dans la colonne la plus a droite
        print(right_pixels_y)
        y_moyen = int(np.mean(right_pixels_y))
        edgex = x + right_col + 4 # On dit que la soudure est un tout petit peu à droite (+4px ici)
        edgey = y + y_moyen

        edge_list.append((edgex,edgey))

        if draw : 
            cv.circle(cimg, (edgex, edgey), 5, (255,0,0),3)

        # #Autre methode, en utilisant des filtres de sobel
        # sobelx = cv.Sobel(region, cv.CV_16S, 1, 0, ksize=3)
        # edges = (sobelx <= -400).astype(np.uint8) * 255
        # # kernel = cv.getStructuringElement(cv.MORPH_RECT, (3,3))
        # # edges = cv.morphologyEx(region, cv.MORPH_OPEN, kernel)
        # magnifying_glass(mask[y:y+h, x:x+w])
        # magnifying_glass(edges)

        # #Autre methode, en utilisant la detection de coins de Harris
        # corners = cv.cornerHarris(region, blockSize=2, ksize=5, k=0.04, borderType=cv.BORDER_CONSTANT)
        # corners = corners[:,50:] # La region que l'on cherche n'est pas dans les 50 premiers pixels, puisqu'elle est au bout droit ici
        # corners = (corners>0.5*corners.max()).astype(np.uint8)*255
        # corners = cv.dilate(corners, cv.getStructuringElement(cv.MORPH_RECT, (3,3)))
        # magnifying_glass(corners)

    if draw:
        magnifying_glass(cimg)

    return short_list, edge_list, labels

In [56]:
find_shorts(path3, draw = True)

[55 56]
[67 68]
[79]
[90]
[103 104]
[92 93 94]
[76 77]
[76]
[72]
[72]
[70]
[69]
[74]
[74 75]
[64 65]
[64 65]
[55 56]
[75 76]
[62 63]
[62 63]
[53]
[51]
[41]
[31]
[39]
--- Magnifying Glass ---
Drag and drop to enhance | Press 'r' to reset view | Press 'q' to finish viewing
--- Magnifying Glass ---
Drag and drop to enhance | Press 'r' to reset view | Press 'q' to finish viewing
[39]
[21]
[41 42]
[34 35]
[31]
[27 28]
[20 21]
[21 22]
[18 19]
[17]
[14]
[14]
[12]
[12]
[12]
[8]
[7]
[6 7]
[6 7]
[5 6]
[6 7]
[6]
[8]
[13]
[18 19 20]
[31 32]
[31]
[18 19]
[16 17]
[15 16]
[15 16 17]
[14 15]
[13]
[ 6  7 13]
[12]
[ 8  9 10]
[8]
[14]
[11 12]
[8]
[7 8]
[6]
[6 7]
[5 6]
[5 6]
[5]
[6 7]
[6 7]
[ 6 11 12]
[6]
[6 7]
[5 6]
[6 7]
[5 7]
[5]
[6]
[5]
[5 6]
[6]
[5 6 7]
[8]
[11 12 13]
[10]
[11 12 13]
[ 9 10]
[27]
[26 27 28]
[32 33 34]
[50 51]
[46]
[56 57]
[75 76]
[75]
[63]
[82]
[68]
[69]
[68 69]
[67 68]
[66 67 68]
[86 87]
[91 92]
[79]
[80 81 82]
[70 71]
[92 93]
[82]
[82]
[71 72]
[66]
[61 62]
[55 56 59 60 61]
[51]
[44

([array([141, 367], dtype=int32),
  array([186, 373], dtype=int32),
  array([ 223, 2957], dtype=int32),
  array([ 133, 4880], dtype=int32),
  array([  70, 4890], dtype=int32)],
 [(np.int64(381), np.int32(72)),
  (np.int64(377), np.int32(97)),
  (np.int64(384), np.int32(122)),
  (np.int64(417), np.int32(146)),
  (np.int64(448), np.int32(171)),
  (np.int64(394), np.int32(174)),
  (np.int64(373), np.int32(183)),
  (np.int64(371), np.int32(195)),
  (np.int64(369), np.int32(204)),
  (np.int64(371), np.int32(217)),
  (np.int64(375), np.int32(228)),
  (np.int64(374), np.int32(239)),
  (np.int64(418), np.int32(257)),
  (np.int64(453), np.int32(270)),
  (np.int64(415), np.int32(272)),
  (np.int64(452), np.int32(286)),
  (np.int64(417), np.int32(289)),
  (np.int64(454), np.int32(322)),
  (np.int64(414), np.int32(322)),
  (np.int64(451), np.int32(335)),
  (np.int64(414), np.int32(338)),
  (np.int64(451), np.int32(349)),
  (np.int64(414), np.int32(352)),
  (np.int64(378), np.int32(354)),
  (np.int

In [25]:
_,_,labels = find_shorts(path1)
labels = (labels % 256).astype(np.uint8) # Processing pour colorier les labels (pas nécessaire)
lut = gen_lut()
rgb = labels2rgb(labels, lut)
magnifying_glass(rgb)

cv.imshow("test",rgb)
cv.waitKey(0)
cv.destroyAllWindows()

--- Magnifying Glass ---
Drag and drop to enhance | Press 'r' to reset view | Press 'q' to finish viewing
--- Magnifying Glass ---
Drag and drop to enhance | Press 'r' to reset view | Press 'q' to finish viewing


In [10]:
def test_sobel(img):
    # Sobel edge detection (horizontal emphasis)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
    sobelx = cv.Sobel(gray, cv.CV_64F, 1, 0, ksize=3)  # Horizontal edges
    sobely = cv.Sobel(gray, cv.CV_64F, 0, 1, ksize=5)  # Vertical edges (for gap detection)

    angles = np.atan2(sobely,sobelx)
    limit_angle = 35 #degrees

    angularmask = cv.threshold(np.abs(angles), 0, np.radians(limit_angle), cv.THRESH_BINARY)[1] + cv.threshold(np.abs(np.pi-angles), 0, np.radians(limit_angle), cv.THRESH_BINARY)[1]

    sobely = cv.convertScaleAbs(sobely)

    # Horizontal wires have strong vertical edges at their boundaries
    edges = cv.threshold(sobely, 80, 255, cv.THRESH_BINARY)[1]
    magnifying_glass(edges)
    print(angles)
    magnifying_glass(cv.bitwise_and(angularmask,edges))
    
    return edges

In [11]:
test_sobel(mask)

--- Magnifying Glass ---
Drag and drop to enhance | Press 'r' to reset view | Press 'q' to finish viewing
[[ 0.          0.          0.         ...  0.          0.
   0.        ]
 [ 1.57079633  1.56510918  1.57294455 ...  1.55889213  1.54428739
   1.57079633]
 [-1.57079633 -1.56665127 -1.58428099 ...  1.56719598  1.57720063
   1.57079633]
 ...
 [-1.57079633 -1.52276764 -1.60126309 ... -1.58028971 -1.56672658
  -1.57079633]
 [-1.57079633 -1.58982956 -1.63629913 ... -1.60280868 -1.5838334
  -1.57079633]
 [ 0.          3.14159265  3.14159265 ...  3.14159265  3.14159265
   0.        ]]


error: OpenCV(4.11.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:214: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and type), nor 'array op scalar', nor 'scalar op array' in function 'cv::binary_op'


--- Magnifying Glass ---
Drag and drop to enhance | Press 'r' to reset view | Press 'q' to finish viewing
